FROM yahboomtechnology/ros-foxy:4.2.0

ARG TARGETARCH
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
ENV ROS_DISTRO=foxy

# mirror repo by bfsu
RUN if [ "$TARGETARCH" = "arm64" ]; then \
        echo "deb https://mirrors.bfsu.edu.cn/ubuntu-ports/ jammy main restricted universe multiverse" > /etc/apt/sources.list; \
        echo "deb https://mirrors.bfsu.edu.cn/ubuntu-ports/ jammy-updates main restricted universe multiverse" >> /etc/apt/sources.list; \
        echo "deb https://mirrors.bfsu.edu.cn/ubuntu-ports/ jammy-backports main restricted universe multiverse" >> /etc/apt/sources.list; \
        echo "deb https://mirrors.bfsu.edu.cn/ubuntu-ports/ jammy-security main restricted universe multiverse" >> /etc/apt/sources.list; \
    else \
        echo "deb https://mirrors.bfsu.edu.cn/ubuntu/ jammy main restricted universe multiverse" > /etc/apt/sources.list; \
        echo "deb https://mirrors.bfsu.edu.cn/ubuntu/ jammy-updates main restricted universe multiverse" >> /etc/apt/sources.list; \
        echo "deb https://mirrors.bfsu.edu.cn/ubuntu/ jammy-backports main restricted universe multiverse" >> /etc/apt/sources.list \
        echo "deb https://mirrors.bfsu.edu.cn/ubuntu/ jammy-security main restricted universe multiverse" >> /etc/apt/sources.list; \
    fi

RUN curl -sSL https://mirror.ghproxy.com/https://raw.githubusercontent.com/ros/rosdistro/master/ros.key  -o /usr/share/keyrings/ros-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] https://mirrors.bfsu.edu.cn/ros2/ubuntu jammy main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null && \
    apt update && \
    apt install -y --no-install-recommends \
    ros-$ROS_DISTRO-ros-core \
    ros-$ROS_DISTRO-demo-nodes-cpp ros-$ROS_DISTRO-demo-nodes-py \
    build-essential git python3-colcon-common-extensions python3-colcon-mixin python3-rosdep python3-vcstool \
    file dirmngr gpg curl gnupg2 htop usbutils zsh tzdata vim tmux git python3-pip xauth  net-tools && \
    curl -o /usr/local/bin/gosu -SL "https://mirror.ghproxy.com/https://github.com/tianon/gosu/releases/latest/download/gosu-$(dpkg --print-architecture)" && \
    chmod +x /usr/local/bin/gosu && \
    apt clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# set workdir
WORKDIR /root

# set entrypoint
COPY entrypoint.sh /entrypoint.sh
RUN chmod a+x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

CMD ["bash"]
